[package]
name = "heartree"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"

[lib]
name = "heartree"
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"
